// Chinese inline comments for SumatraPDF-settings.txt serialization (Plus fork).
// Keys: "FieldName" for GlobalPrefs, "StructName.FieldName" for nested settings.

export const settingsInlineCommentsZh: Record<string, string> = {
  CheckForUpdates: "是否每天自动检测新版本",
  CustomScreenDPI: "自定义主屏幕 DPI；0=跟随系统",
  DefaultDisplayMode: "默认页面布局",
  DefaultZoom: "默认缩放",
  EnableTeXEnhancements: "显示 LaTeX SyncTeX 反向搜索命令行",
  InverseSearchCmdLine: "LaTeX 反向搜索命令行",
  EscToExit: "true=按 Esc 直接关闭窗口",
  FullPathInTitle: "标题栏显示完整路径",
  LazyLoading: "恢复会话时延迟加载未选中标签页",
  MainWindowBackground: "文档外侧空白区域底色 #AARRGGBB",
  NoHomeTab: "标签模式下不显示首页标签",
  HomePageSortByFrequentlyRead: "首页按打开次数排序",
  HomePageViewMode: "首页视图 thumbnails/list",
  HomePageThumbnailDx: "首页缩略图首选宽度（像素），会略微伸缩铺满窗口；列表视图不受影响；有效范围 160-280",
  ReloadModifiedDocuments: "外部修改后自动重载",
  RememberOpenedFiles: "记录打开过的文件",
  RememberStatePerDocument: "为每个文档单独保存阅读进度",
  RestoreSession: "启动时恢复上次会话",
  ReuseInstance: "新文件在已有窗口打开",
  ShowMenubar: "非标签模式下显示菜单栏",
  ShowMenubarWithTabs: "标签模式下显示菜单栏",
  ShowTips: "在首页显示使用技巧",
  CustomColors: "背景色选择器自定义颜色",
  ShowToolbar: "显示顶部工具栏",
  ShowAnnotToolbarButtons: "工具栏显示矩形/椭圆/直线/画笔快捷标注按钮",
  SearchUIFloating: "true=悬浮搜索窗口",
  OfflineDictionaryPath: "离线词典目录",
  AutoOcrScanPages: "自动识别无文字层的扫描页，便于选择和搜索；模型在 {exedir}/ocr/",
  OcrAutoSave: "全文识别或提取目录完成后覆盖保存当前 PDF",
  OcrFullDocumentMode: "全文识别模式 fast=极速 accurate=高精度；自动 OCR 使用极速，框选/当前页使用高精度",
  ExtractPdfTocMode: "智能提取目录详细程度 conservative/standard/detailed",
  EnableDoubleClickWordLookup: "双击查离线词典",
  AiChatProvider: "Ask AI 提供商 doubao/deepseek/chatgpt",
  AiChatUseDeepSeekInsteadOfDoubao: "已弃用，请用 AiChatProvider",
  EnableAskAI: "显示 Ask AI 入口",
  EnableInlineTranslate: "显示划词翻译入口",
  TranslateVolcAccessKey: "火山翻译 Access Key（可 DPAPI 加密）",
  TranslateVolcSecretKey: "火山翻译 Secret Key（可 DPAPI 加密）",
  TranslateTargetMode: "划词翻译目标语 auto/ui/zh/zh-Hant/en/ja/ko/…",
  ShowFavorites: "默认显示收藏侧边栏",
  ShowToc: "默认显示目录侧边栏",
  ShowLinks: "为链接绘制蓝色边框",
  ShowStartPage: "无文档时显示最近文件",
  SidebarDx: "侧边栏宽度，0=默认",
  Scrollbars: "滚动条 windows/smart/overlay/hidden",
  ScrollbarInSinglePage: "单页模式显示滚动条",
  SmoothScroll: "平滑滚动",
  FastScrollOverScrollbar: "滚轮在滚动条区域时半页滚动",
  PreventSleepInFullscreen: "全屏/演示时阻止休眠",
  TabWidth: "单个标签最大宽度",
  TabFontSize: "标签栏字号（0=自动）",
  TabBarHeight: "标签栏高度（0=自动）",
  Theme: "当前主题",
  LastDarkTheme: "切换到深色模式时的主题",
  LastLightTheme: "切换到浅色模式时的主题",
  DocumentColorMode: "文档颜色模式 original/theme（原稿/匹配主题）",
  TocDy: "目录区高度（与收藏同显时）",
  ToolbarSize: "工具栏高度",
  TreeFontName: "目录/收藏树字体",
  TreeFontSize: "目录/收藏树字号",
  TreeWrapLabels: "true=书签/收藏长标题多行换行；false=单行省略+悬停显示全文",
  UIFontSize: "界面字体大小",
  DisableAntiAlias: "关闭 PDF 抗锯齿",
  EngineeringDrawingEnhance: "工程图纸增强 off/auto/on",
  UseSysColors: "使用 Windows 系统主题色",
  UseTabs: "启用标签页",
  TabsMru: "Ctrl+Tab 按最近使用排序",
  ZoomLevels: "自定义缩放档位",
  ZoomIncrement: "滚轮缩放步长",
  FixedPageUI: "PDF/XPS/DjVu 界面",
  "FixedPageUI.TextColor": "文字颜色",
  "FixedPageUI.BackgroundColor": "页面底色",
  "FixedPageUI.SelectionColor": "选中高亮色",
  "FixedPageUI.SelectionHeightRatio": "选中文字背景高度比例 0.5-1.5，越小越薄",
  "FixedPageUI.WindowMargin": "页边距 上 右 下 左",
  "FixedPageUI.PageSpacing": "页面间距 横 纵",
  "FixedPageUI.InvertColors": "全局反色",
  "FixedPageUI.WindowBgCol": "PDF 画布背景色",
  "FixedPageUI.FindMatchColor": "查找匹配高亮色",
  EBookUI: "EPUB/MOBI 电子书界面",
  "EBookUI.FontSize": "6–26 之间的数字，单位是磅（pt）；0=内置默认；超出范围无效",
  "EBookUI.FontFamily": "电子书西文/默认衬线字体",
  "EBookUI.CjkFontFamily": "电子书中文正文字体",
  "EBookUI.LayoutDx": "页面宽度 pt",
  "EBookUI.LayoutDy": "页面高度 pt",
  "EBookUI.IgnoreDocumentCSS": "忽略文档 CSS",
  "EBookUI.CustomCSS": "自定义 CSS",
  "EBookUI.EpubProgressiveLoad": "EPUB 渐进加载",
  "EBookUI.EpubPerfLog": "EPUB 性能日志",
  "EBookUI.WindowBgCol": "电子书画布背景色",
  ComicBookUI: "CBZ/CBR 漫画界面",
  "ComicBookUI.WindowMargin": "漫画页边距",
  "ComicBookUI.PageSpacing": "漫画分页间距",
  "ComicBookUI.CbxMangaMode": "日式右向左阅读",
  "ComicBookUI.WindowBgCol": "漫画画布背景色",
  ImageUI: "图片文件界面",
  "ImageUI.WindowBgCol": "图片画布背景色",
  "ImageUI.DefaultZoom": "打开图片默认缩放",
  ChmUI: "CHM 帮助文档界面",
  "ChmUI.UseFixedPageUI": "true=使用 PDF 式布局",
  Annotations: "注释默认样式",
  "Annotations.HighlightColor": "高亮颜色",
  "Annotations.UnderlineColor": "下划线颜色",
  "Annotations.SquigglyColor": "波浪线颜色",
  "Annotations.StrikeOutColor": "删除线颜色",
  "Annotations.FreeTextColor": "文本批注文字色",
  "Annotations.FreeTextBackgroundColor": "文本批注背景色",
  "Annotations.FreeTextOpacity": "批注不透明度 0-100",
  "Annotations.FreeTextSize": "文本批注字号",
  "Annotations.FreeTextBorderWidth": "批注边框粗细",
  "Annotations.TextIconColor": "批注图标颜色",
  "Annotations.TextIconType": "批注图标类型",
  "Annotations.DefaultAuthor": "新建注释默认作者",
  "Annotations.SelectionToolbar": "选中文字后显示划词工具栏",
  ExternalViewers: "外部程序打开方式",
  "ExternalViewer.CommandLine": "外部程序命令行",
  "ExternalViewer.Name": "菜单显示名称",
  "ExternalViewer.Filter": "文件类型过滤",
  "ExternalViewer.Key": "快捷键",
  "ExternalViewer.ToolbarText": "工具栏文字",
  ForwardSearch: "SyncTeX 正向搜索高亮",
  "ForwardSearch.HighlightOffset": "高亮条左边距",
  "ForwardSearch.HighlightWidth": "高亮条宽度",
  "ForwardSearch.HighlightColor": "高亮颜色",
  "ForwardSearch.HighlightPermanent": "高亮保持到下次点击",
  PrinterDefaults: "打印默认参数",
  "PrinterDefaults.PrintScale": "打印缩放 shrink/fit/none",
  Fullscreen: "全屏模式设置",
  "Fullscreen.ShowToolbar": "全屏时显示工具栏",
  "Fullscreen.ShowMenubar": "全屏时显示菜单栏",
  SelectionHandlers: "选中文字自定义搜索",
  "SelectionHandler.URL": "搜索 URL",
  "SelectionHandler.Name": "菜单名称",
  "SelectionHandler.Key": "快捷键",
  Shortcuts: "自定义快捷键",
  "Shortcut.Cmd": "命令",
  "Shortcut.Key": "快捷键",
  "Shortcut.Name": "命令面板名称",
  "Shortcut.ToolbarText": "工具栏文字",
  Themes: "自定义主题",
  "Theme.Name": "主题名称",
  "Theme.TextColor": "文字颜色",
  "Theme.BackgroundColor": "背景颜色",
  "Theme.ControlBackgroundColor": "控件背景色",
  "Theme.LinkColor": "链接颜色",
  "Theme.ColorizeControls": "着色 Windows 控件",
  TabGroups: "标签分组",
  "TabGroup.Name": "分组名称",
  ReadAloudVoiceId: "朗读语音 ID",
  ReadAloudSpeakingRate: "朗读语速（旧）",
  ReadAloudSpeakingRateZh: "中文朗读语速",
  ReadAloudSpeakingRateEn: "英文朗读语速",
  ReadAloudSmartVoiceZh: "本地智能中文语音",
  ReadAloudSmartVoiceEn: "本地智能英文语音",
  ReadAloudSmartOnlineVoiceZh: "在线智能中文语音",
  ReadAloudSmartOnlineVoiceEn: "在线智能英文语音",
  ReadAloudMultilingualVoice: "在线多语言语音",
  ReadAloudHighlightColor: "朗读高亮色",
  ReadAloudAutoFollow: "朗读时自动跟随",
  NarrationUseBookAudio: "有声书使用书内录音",
  NarrationUseBookHighlightColor: "有声书使用书内高亮色",
  NarrationSpeed: "有声书播放倍速",
  UiLanguage: "界面语言",
  WindowState: "窗口状态 1正常 2最大化 3全屏 4最小化",
  WindowPos: "窗口位置与尺寸",
  SearchUIWindowPos: "悬浮搜索窗位置",
  FileStates: "各文档阅读状态",
  "FileState.DisplayFilterBrightness": "该文档页面亮度（-100..100，0=预设基线）",
  "FileState.DisplayFilterContrast": "该文档页面对比度（-100..100，0=预设基线）",
  "FileState.DisplayFilterSharpness": "该文档页面锐度（0..100，0=预设基线）",
  "FileState.DisplayFilterMode": "该文档显示增强模式（0=关闭，1=旧版，2=阅读，3=扫描件）",
  SessionData: "上次会话数据",
  TimeOfLastUpdateCheck: "上次检测更新时间",
  TimeOfUpdateCheckSnooze: "更新提示推迟时间",
  OpenCountWeek: "本周打开次数统计",
};
