// !!!!! This file is auto-generated by do/settings_gen_code.go

/* Copyright 2022 the SumatraPDF project authors (see AUTHORS file).
   License: Simplified BSD (see COPYING) */

struct RenderedBitmap;

enum class DisplayMode {
    // automatic means: the continuous form of single page, facing or
    // book view - depending on the document's desired PageLayout
    Automatic = 0,
    SinglePage,
    Facing,
    BookView,
    Continuous,
    ContinuousFacing,
    ContinuousBookView,
};

constexpr float kZoomFitPage = -1.F;
constexpr float kZoomFitWidth = -2.F;
constexpr float kZoomFitContent = -3.F;
constexpr float kZoomShrinkToFit = -4.F;
constexpr float kZoomActualSize = 100.0F;
constexpr float kZoomMax = 6400.F; /* max zoom in % */
constexpr float kZoomMin = 8.33F;  /* min zoom in % */
constexpr float kInvalidZoom = -99.0F;

// top, right, bottom and left margin (in that order) between window and
// document
struct WindowMargin {
    // size of the top margin between window and document
    int top;
    // size of the right margin between window and document
    int right;
    // size of the bottom margin between window and document
    int bottom;
    // size of the left margin between window and document
    int left;
};

// customization options for PDF, XPS, DjVu and PostScript UI
struct FixedPageUI {
    // color value with which black (text) will be substituted
    char* textColor;
    ParsedColor textColorParsed;
    // color value with which white (background) will be substituted
    char* backgroundColor;
    ParsedColor backgroundColorParsed;
    // color value for the text selection rectangle. Use an #aarrggbb value
    // to control opacity: a smaller alpha (e.g. #40ffff00) makes the
    // selection more transparent so the selected text stays crisp; #rrggbb
    // uses the default opacity
    char* selectionColor;
    ParsedColor selectionColorParsed;
    // height of the text selection background relative to its glyph band;
    // 0.5-1.5, default 1.0; smaller values make it thinner
    float selectionHeightRatio;
    // top, right, bottom and left margin (in that order) between window
    // and document
    WindowMargin windowMargin;
    // horizontal and vertical distance between two pages in facing and
    // book view modes
    Size pageSpacing;
    // colors to use for the gradient from top to bottom (stops will be
    // inserted at regular intervals throughout the document); currently
    // only up to three colors are supported; the idea behind this
    // experimental feature is that the background might allow to
    // subconsciously determine reading progress; suggested values: #2828aa
    // #28aa28 #aa2828
    Vec<char*>* gradientColors;
    // if true, TextColor and BackgroundColor of the document will be
    // swapped
    bool invertColors;
    // if given, sets the canvas background color for PDF files
    char* windowBgCol;
    ParsedColor windowBgColParsed;
    // color used to highlight the current search match on the page
    char* findMatchColor;
    ParsedColor findMatchColorParsed;
    // if true, join Calibre-style split photos: paint the clipped-off
    // strip onto the keeper page and hide the redundant thin-strip page
    bool joinSplitPdfImages;
};

// customization options for eBookUI
struct EBookUI {
    // ebook body font size in points; 0 uses built-in default (~11 pt),
    // 6-26 forces this size (out of range ignored)
    float fontSize;
    // default Latin/serif body font for reflowable ebooks (EPUB, MOBI).
    // Empty uses Literata
    char* fontFamily;
    // default CJK body font for reflowable ebooks. Empty uses Source Han
    // Serif SC
    char* cjkFontFamily;
    // optional override: bundled CJK font file in fonts\ when auto-detect
    // by CjkFontFamily fails
    char* cjkFontFile;
    // page width in pt for flowed ebooks. 0 means automatic reader-style
    // width
    float layoutDx;
    // page height in pt for flowed ebooks. 0 means automatic reader-style
    // height
    float layoutDy;
    // if true, we ignore ebook's CSS
    bool ignoreDocumentCSS;
    // custom CSS. Might need to set IgnoreDocumentCSS = true
    char* customCSS;
    // if true, large reflowable EPUBs count chapters in the background for
    // faster first paint
    bool epubProgressiveLoad;
    // if true, emit structured EPUB performance events as JSON lines in
    // the log
    bool epubPerfLog;
    // if given, sets the canvas background color for ebook documents
    // (epub, mobi etc.)
    char* windowBgCol;
    ParsedColor windowBgColParsed;
};

// customization options for Comic Book UI
struct ComicBookUI {
    // top, right, bottom and left margin (in that order) between window
    // and document
    WindowMargin windowMargin;
    // horizontal and vertical distance between two pages in facing and
    // book view modes
    Size pageSpacing;
    // if true, default to displaying Comic Book files in manga mode (from
    // right to left if showing 2 pages at a time)
    bool cbxMangaMode;
    // if given, sets the canvas background color for comic book files
    char* windowBgCol;
    ParsedColor windowBgColParsed;
};

// customization options for image files UI
struct ImageUI {
    // if given, sets the canvas background color for image files
    char* windowBgCol;
    ParsedColor windowBgColParsed;
    // default zoom for image files. valid values: fit page, fit width, fit
    // content, shrink to fit or percent like 100%
    char* defaultZoom;
    // value of DefaultZoom for internal usage
    float defaultZoomFloat;
};

// customization options for CHM UI. If UseFixedPageUI is true,
// FixedPageUI settings apply instead
struct ChmUI {
    // if true, the UI used for PDF documents will be used for CHM
    // documents as well
    bool useFixedPageUI;
};

// default values for annotations in PDF documents
struct Annotations {
    // highlight annotation color
    char* highlightColor;
    ParsedColor highlightColorParsed;
    // underline annotation color
    char* underlineColor;
    ParsedColor underlineColorParsed;
    // squiggly annotation color
    char* squigglyColor;
    ParsedColor squigglyColorParsed;
    // strike out annotation color
    char* strikeOutColor;
    ParsedColor strikeOutColorParsed;
    // text color of free text annotation
    char* freeTextColor;
    ParsedColor freeTextColorParsed;
    // background color of free text annotation
    char* freeTextBackgroundColor;
    ParsedColor freeTextBackgroundColorParsed;
    // opacity of free text annotation in percent (0-100); 0 - fully
    // transparent (invisible), 50 - half transparent, 100 - fully opaque
    int freeTextOpacity;
    // size of free text annotation
    int freeTextSize;
    // width of free text annotation border
    int freeTextBorderWidth;
    // text icon annotation color
    char* textIconColor;
    ParsedColor textIconColorParsed;
    // type of text annotation icon: comment, help, insert, key, new
    // paragraph, note, paragraph. If not set: note.
    char* textIconType;
    // default author for created annotations, use (none) to not add an
    // author at all. If not set will use Windows user name
    char* defaultAuthor;
    // if true, a small toolbar with annotation actions (highlight,
    // underline etc.) and Ask AI pops up after selecting text in PDF
    // documents that support annotations. Set to false to disable it
    bool selectionToolbar;
};

// list of additional external viewers for various file types. See [docs
// for more
// information](https://www.sumatrapdfreader.org/docs/Customize-external-viewers)
struct ExternalViewer {
    // command line with which to call the external viewer, may contain %p
    // for page number and "%1" for the file name (add quotation marks
    // around paths containing spaces)
    char* commandLine;
    // name of the external viewer to be shown in the menu (implied by
    // CommandLine if missing)
    char* name;
    // optional filter for which file types the menu item is to be shown;
    // separate multiple entries using ';' and don't include any spaces
    // (e.g. *.pdf;*.xps for all PDF and XPS documents)
    char* filter;
    // optional: keyboard shortcut e.g. Alt + 7
    char* key;
    // if given, shows in toolbar
    char* toolbarText;
};

// customization options for how we show forward search results (used
// from LaTeX editors)
struct ForwardSearch {
    // when set to a positive value, the forward search highlight style
    // will be changed to a rectangle at the left of the page (with the
    // indicated amount of margin from the page margin)
    int highlightOffset;
    // width of the highlight rectangle (if HighlightOffset is > 0)
    int highlightWidth;
    // color used for the forward search highlight
    char* highlightColor;
    ParsedColor highlightColorParsed;
    // if true, highlight remains visible until the next mouse click
    // (instead of fading away immediately)
    bool highlightPermanent;
};

// these override the default settings in the Print dialog
struct PrinterDefaults {
    // default value for scaling (shrink, fit, none)
    char* printScale;
};

// options for fullscreen mode
struct Fullscreen {
    // if true, show the toolbar in fullscreen mode
    bool showToolbar;
    // if true, show the menu bar in fullscreen mode
    bool showMenubar;
};

// list of handlers for selected text, shown in context menu when text
// selection is active. See [docs for more
// information](https://www.sumatrapdfreader.org/docs/Customize-search-translation-services)
struct SelectionHandler {
    // url to invoke for the selection. ${selection} will be replaced with
    // current selection and ${userlang} with language code for current UI
    // (e.g. 'de' for German)
    char* url;
    // name shown in context menu
    char* name;
    // keyboard shortcut
    char* key;
};

// custom keyboard shortcuts
struct Shortcut {
    // command
    char* cmd;
    // keyboard shortcut (e.g. Ctrl-Alt-F)
    char* key;
    // name shown in command palette
    char* name;
    // if given, shows in toolbar
    char* toolbarText;
    // command id
    int cmdId;
};

// color themes
struct Theme {
    // name of the theme
    char* name;
    // text color
    char* textColor;
    ParsedColor textColorParsed;
    // background color
    char* backgroundColor;
    ParsedColor backgroundColorParsed;
    // control background color
    char* controlBackgroundColor;
    ParsedColor controlBackgroundColorParsed;
    // link color
    char* linkColor;
    ParsedColor linkColorParsed;
    // should we colorize Windows controls and window areas
    bool colorizeControls;
};

// files in the tab group
struct TabFile {
    // file path
    char* path;
};

// saved groups of tabs
struct TabGroup {
    // name of the tab group
    char* name;
    // files in the tab group
    Vec<TabFile*>* tabFiles;
};

// Values which are persisted for bookmarks/favorites
struct Favorite {
    // name of this favorite as shown in the menu
    char* name;
    // number of the bookmarked page
    int pageNo;
    // label for this page (only present if logical and physical page
    // numbers are not the same)
    char* pageLabel;
    // sequence number assigned when this favorite was added. Lower numbers
    // sort first in the added-order view
    int addedSeq;
    // id of this favorite in the menu (assigned by AppendFavMenuItems)
    int menuId;
};

// information about opened files (in most recently used order)
struct FileState {
    // path of the document
    char* filePath;
    // Values which are persisted for bookmarks/favorites
    Vec<Favorite*>* favorites;
    // a document can be "pinned" to the Frequently Read list so that it
    // isn't displaced by recently opened documents
    bool isPinned;
    // if a document can no longer be found but we still remember valuable
    // state, it's classified as missing so that it can be hidden instead
    // of removed
    bool isMissing;
    // in order to prevent documents that haven't been opened for a while
    // but used to be opened very frequently constantly remain in top
    // positions, the openCount will be cut in half after every week, so
    // that the Frequently Read list hopefully better reflects the
    // currently relevant documents
    int openCount;
    // Hex encoded MD5 fingerprint of file content (32 chars) followed by
    // crypt key (64 chars) - only applies for PDF documents
    char* decryptionKey;
    // if true, we use global defaults when opening this file (instead of
    // the values below)
    bool useDefaultState;
    // how pages should be laid out for this document, needs to be
    // synchronized with DefaultDisplayMode after deserialization and
    // before serialization
    char* displayMode;
    // how far this document has been scrolled (in x and y direction)
    PointF scrollPos;
    // number of the last read page
    int pageNo;
    // zoom (in %) or one of those values: fit page, fit width, fit content
    char* zoom;
    // how far pages have been rotated as a multiple of 90 degrees
    int rotation;
    // state of the window. 1 is normal, 2 is maximized, 3 is fullscreen, 4
    // is minimized
    int windowState;
    // default position (can be on any monitor)
    Rect windowPos;
    // if true, we show table of contents (Bookmarks) sidebar if it's
    // present in the document
    bool showToc;
    // which sidebar view was showing for this document: bookmarks,
    // thumbnails, or favorites
    char* sidebarView;
    // width of the left sidebar panel containing the table of contents
    int sidebarDx;
    // if true, the document is displayed right-to-left in facing and book
    // view modes (only used for comic book documents)
    bool displayR2L;
    // if given, overrides the background color for this document
    char* bgCol;
    ParsedColor bgColParsed;
    // if given, overrides the tab color for this document
    char* tabCol;
    ParsedColor tabColParsed;
    // page display brightness for this document (-100..100). 0 means no
    // change
    int displayFilterBrightness;
    // page display contrast for this document (-100..100). 0 means no
    // change
    int displayFilterContrast;
    // page display sharpness for this document (0..100). 0 means off
    int displayFilterSharpness;
    // page display enhancement mode for this document (0=off, 4=auto
    // Mild/Strong; 1/2/3 migrate to auto)
    int displayFilterMode;
    // toolbar auto OCR for this document. Never inferred from a missing
    // text layer; the user turns it on per file
    bool autoOcrOn;
    // index into an ebook's HTML data from which reparsing has to happen
    // in order to restore the last viewed page (i.e. the equivalent of
    // PageNo for the ebook UI)
    int reparseIdx;
    // tocState is an array of ids for ToC items that have been toggled by
    // the user (i.e. aren't in their default expansion state). - Note: We
    // intentionally track toggle state as opposed to expansion state so
    // that we only have to save a diff instead of all states for the whole
    // tree (which can be quite large) (internal)
    Vec<int>* tocState;
    // thumbnails are saved as PNG files in sumatrapdfcache directory
    RenderedBitmap* thumbnail;
    // runtime-only: whether thumbnail was generated for dark theme
    bool thumbnailDarkTheme;
    // runtime-only: cached result of IsThumbnailMostlyBlank
    bool thumbnailBlankKnown;
    // runtime-only: whether thumbnail is mostly blank
    bool thumbnailIsBlank;
    // temporary value needed for FileHistory::cmpOpenCount
    size_t index;
    //
    HIMAGELIST himl;
    //
    int iconIdx;
    // runtime-only: cached file::GetSize for homepage list rows
    bool homePageSizeKnown;
    // runtime-only: cached file size in bytes
    i64 homePageFileSize;
};

// a subset of FileState required for restoring the state of a single
// tab (required for handling documents being opened twice)
struct TabState {
    // path of the document
    char* filePath;
    // same as FileStates -> DisplayMode
    char* displayMode;
    // number of the last read page
    int pageNo;
    // same as FileStates -> Zoom
    char* zoom;
    // same as FileStates -> Rotation
    int rotation;
    // how far this document has been scrolled (in x and y direction)
    PointF scrollPos;
    // if true, the table of contents was shown when the document was
    // closed
    bool showToc;
    // same as FileStates -> TocState
    Vec<int>* tocState;
};

// state of the last session, usage depends on RestoreSession
struct SessionData {
    // a subset of FileState required for restoring the state of a single
    // tab (required for handling documents being opened twice)
    Vec<TabState*>* tabStates;
    // index of the currently selected tab (1-based)
    int tabIndex;
    // same as FileState -> WindowState
    int windowState;
    // default position (can be on any monitor)
    Rect windowPos;
    // width of favorites/bookmarks sidebar (if shown)
    int sidebarDx;
};

// Preferences are persisted in SumatraPDF-settings.txt
struct GlobalPrefs {
    // if true, we check once a day if an update is available
    bool checkForUpdates;
    // actual resolution of the main screen in DPI (if this value isn't
    // positive, the system's UI setting is used)
    int customScreenDPI;
    // how pages should be laid out by default, needs to be synchronized
    // with DefaultDisplayMode after deserialization and before
    // serialization
    char* defaultDisplayMode;
    // default zoom. valid values: fit page, fit width, fit content or
    // percent like 100%
    char* defaultZoom;
    // if true, we expose the SyncTeX inverse search command line in
    // Settings -> Options
    bool enableTeXEnhancements;
    // if true, Esc key closes SumatraPDF
    bool escToExit;
    // if true, we show the full path to a file in the title bar
    bool fullPathInTitle;
    // pattern used to launch the LaTeX editor when doing inverse search
    char* inverseSearchCmdLine;
    // when restoring session, delay loading of documents until their tab
    // is selected
    bool lazyLoading;
    // background color of the non-document windows, traditionally yellow
    char* mainWindowBackground;
    ParsedColor mainWindowBackgroundParsed;
    // if true, doesn't open Home tab
    bool noHomeTab;
    // if true implements pre-3.6 behavior of showing opened files by
    // frequently used count. If false, shows most recently opened first
    bool homePageSortByFrequentlyRead;
    // home page file list layout: thumbnails (grid with previews) or list
    // (filename and path)
    char* homePageViewMode;
    // preferred home page thumbnail width in pixels; layout grows or
    // shrinks slightly so the grid fills the window. List view is
    // unchanged. Valid range: 160-280
    int homePageThumbnailDx;
    // if true, a document will be reloaded automatically whenever it's
    // changed (currently doesn't work for documents shown in the ebook UI)
    bool reloadModifiedDocuments;
    // if true, we remember which files we opened and their display
    // settings
    bool rememberOpenedFiles;
    // if true, we store display settings for each document separately
    // (i.e. everything after UseDefaultState in FileStates)
    bool rememberStatePerDocument;
    // if true and SessionData isn't empty, that session will be restored
    // at startup
    bool restoreSession;
    // if true, we'll always open files using existing SumatraPDF process
    bool reuseInstance;
    // if false, the menu bar will be hidden (use F9 to toggle, persisted
    // across sessions)
    bool showMenubar;
    // if true, show the menu bar when using tabs (useTabs = true)
    bool showMenubarWithTabs;
    // if true, we show tips on the home page
    bool showTips;
    // up to 13 custom colors for the background color picker, separated by
    // space (e.g. '#ff0000 #00ff00 #0000ff')
    char* customColors;
    // if true, we show the toolbar at the top of the window
    bool showToolbar;
    // if true, show rectangle/ellipse/line/ink quick annotation buttons on
    // the toolbar
    bool showAnnotToolbarButtons;
    // if true, the find UI is a floating, movable window with a results
    // list instead of the compact toolbar overlay
    bool searchUIFloating;
    // directory containing SumatraDict.* dictionary files. If empty,
    // {exedir}/dict is used
    char* offlineDictionaryPath;
    // if true, double-clicking a word looks it up in the offline
    // dictionary
    bool enableDoubleClickWordLookup;
    // if true, automatically OCR scanned pages with little or no text so
    // they can be selected and searched. Models live in {exedir}/ocr/
    bool autoOcrScanPages;
    // if true, overwrite the current PDF after Recognize All Scanned Pages
    // and after extracting bookmarks
    bool ocrAutoSave;
    // if true, straighten slightly tilted scan pages before OCR (and when
    // running Deskew All Scanned Pages heuristics)
    bool ocrDeskew;
    // full-document OCR mode for Recognize All Scanned Pages and Save as
    // Searchable PDF: fast or accurate. Auto OCR uses fast mode; current
    // page and region use high accuracy.
    char* ocrFullDocumentMode;
    // if true, copy of OCR results merges soft-wrapped lines into coherent
    // paragraphs instead of following the original page layout
    bool ocrCopyMerged;
    // smart bookmark extraction detail: conservative, standard, or
    // detailed
    char* extractPdfTocMode;
    // Ask AI provider: doubao (豆包), deepseek, or chatgpt
    char* aiChatProvider;
    // AI table of contents API base URL
    char* aiTocApiBaseUrl;
    // AI table of contents API key
    char* aiTocApiKey;
    // AI table of contents model
    char* aiTocApiModel;
    // saved AI table of contents API profiles (JSON)
    char* aiTocApiProfiles;
    // maximum simultaneous AI table of contents requests (1-8)
    int aiTocApiConcurrency;
    // deprecated: use AiChatProvider instead; if true and AiChatProvider
    // is not in settings, migrates to deepseek
    bool aiChatUseDeepSeekInsteadOfDoubao;
    // if false, hide Ask AI (online chat) in the selection toolbar,
    // context menu, and command palette
    bool enableAskAI;
    // if false, hide Translate in the selection toolbar, context menu, and
    // command palette
    bool enableInlineTranslate;
    // Volcengine Translate access key (Access Key ID); stored
    // DPAPI-protected when possible
    char* translateVolcAccessKey;
    // Volcengine Translate secret key; stored DPAPI-protected when
    // possible
    char* translateVolcSecretKey;
    // inline translate target language: auto (UI language, flip when
    // source matches), ui, or a language code (zh, zh-Hant, en, ja, ko,
    // fr, de, es, ru, ...)
    char* translateTargetMode;
    // if true, we show the Favorites sidebar
    bool showFavorites;
    // if true, we show table of contents (Bookmarks) sidebar if it's
    // present in the document
    bool showToc;
    // if true we draw a blue border around links in the document
    bool showLinks;
    // if true, we show a list of frequently read documents when no
    // document is loaded
    bool showStartPage;
    // width of favorites/bookmarks sidebar (if shown)
    int sidebarDx;
    // scrollbar mode: windows (standard Windows scrollbar), smart (overlay
    // scrollbar with auto-hide), overlay (always visible overlay
    // scrollbar), hidden (no scrollbars)
    char* scrollbars;
    // if true, we show scrollbar in single page mode
    bool scrollbarInSinglePage;
    // if true, implements smooth scrolling
    bool smoothScroll;
    // if true, mouse wheel scrolling is faster when mouse is over a
    // scrollbar
    bool fastScrollOverScrollbar;
    // if true, prevents the screen from turning off when in fullscreen or
    // presentation mode
    bool preventSleepInFullscreen;
    // maximum width of a single tab
    int tabWidth;
    // font size for the tab bar. 0 means use UIFontSize / Windows default
    int tabFontSize;
    // height of the tab bar in DIPs. 0 means automatic from font size
    // (default ~24)
    int tabBarHeight;
    // the name of the theme to use
    char* theme;
    // the dark theme to use when toggling from light mode
    char* lastDarkTheme;
    // the light theme to use when toggling from dark mode
    char* lastLightTheme;
    // document color mode for readable formats (PDF, EPUB, MOBI, CHM, XPS,
    // DjVu, Markdown, etc.): original (publisher colors unchanged) or
    // theme (match current UI theme)
    char* documentColorMode;
    // how images are treated when a dark theme is on and document color
    // mode is Match theme
    char* documentImageDarkStrategy;
    // if both favorites and bookmarks parts of sidebar are visible, this
    // is the height of bookmarks (table of contents) part
    int tocDy;
    // height of toolbar
    int toolbarSize;
    // font name for bookmarks and favorites tree views. automatic means
    // Windows default
    char* treeFontName;
    // font size for bookmarks and favorites tree views. 0 means Windows
    // default
    int treeFontSize;
    // if true, bookmark and favorites tree labels wrap to multiple lines;
    // if false, single line with ellipsis and full text in tooltip on
    // hover
    bool treeWrapLabels;
    // over-ride application font size. 0 means Windows default
    int uIFontSize;
    // if true, disables anti-aliasing for rendering PDF documents
    bool disableAntiAlias;
    // CAD/engineering PDF line display: off, auto (detect), or on
    char* engineeringDrawingEnhance;
    // if true, we use Windows system colors for background/text color.
    // Over-rides other settings
    bool useSysColors;
    // if true, documents are opened in tabs instead of new windows
    bool useTabs;
    // if true, Ctrl+Tab and Ctrl+Shift+Tab show the tab switcher in most
    // recently used order instead of tab-strip order
    bool tabsMru;
    // zoom levels which zooming steps through in addition to Fit Page, Fit
    // Width and the minimum and maximum allowed values (8.33 and 6400)
    Vec<float>* zoomLevels;
    //
    Vec<int>* zoomLevelsCmdIds;
    // zoom step size in percents relative to the current zoom level. if
    // zero or negative, the values from ZoomLevels are used instead
    float zoomIncrement;
    // customization options for PDF, XPS, DjVu and PostScript UI
    FixedPageUI fixedPageUI;
    // customization options for eBookUI
    EBookUI eBookUI;
    // customization options for Comic Book UI
    ComicBookUI comicBookUI;
    // customization options for image files UI
    ImageUI imageUI;
    // customization options for CHM UI. If UseFixedPageUI is true,
    // FixedPageUI settings apply instead
    ChmUI chmUI;
    // default values for annotations in PDF documents
    Annotations annotations;
    // list of additional external viewers for various file types. See
    // [docs for more
    // information](https://www.sumatrapdfreader.org/docs/Customize-external-viewers)
    Vec<ExternalViewer*>* externalViewers;
    // customization options for how we show forward search results (used
    // from LaTeX editors)
    ForwardSearch forwardSearch;
    // these override the default settings in the Print dialog
    PrinterDefaults printerDefaults;
    // options for fullscreen mode
    Fullscreen fullscreen;
    // list of handlers for selected text, shown in context menu when text
    // selection is active. See [docs for more
    // information](https://www.sumatrapdfreader.org/docs/Customize-search-translation-services)
    Vec<SelectionHandler*>* selectionHandlers;
    // custom keyboard shortcuts
    Vec<Shortcut*>* shortcuts;
    // color themes
    Vec<Theme*>* themes;
    // saved groups of tabs
    Vec<TabGroup*>* tabGroups;
    // voice id for Read Aloud text-to-speech; empty or unset means system
    // default. Voice ids match those used internally by the Read Aloud
    // Voice menu (WinRT voice id or SAPI token id)
    char* readAloudVoiceId;
    // legacy single speaking rate; kept for migration, prefer
    // ReadAloudSpeakingRateZh/En
    float readAloudSpeakingRate;
    // speaking rate for Chinese text in Read Aloud; 1.0 is normal speed
    float readAloudSpeakingRateZh;
    // speaking rate for English text in Read Aloud; 1.0 is normal speed
    float readAloudSpeakingRateEn;
    // voice id of the Chinese voice used by local smart bilingual Read
    // Aloud; empty or unset means auto-pick best local Chinese voice
    char* readAloudSmartVoiceZh;
    // voice id of the English voice used by local smart bilingual Read
    // Aloud; empty or unset means auto-pick best local English voice
    char* readAloudSmartVoiceEn;
    // voice id of the Chinese voice used by online smart bilingual Read
    // Aloud; empty or unset means auto-pick best online Chinese voice
    char* readAloudSmartOnlineVoiceZh;
    // voice id of the English voice used by online smart bilingual Read
    // Aloud; empty or unset means auto-pick best online English voice
    char* readAloudSmartOnlineVoiceEn;
    // voice id used by online multilingual Read Aloud; empty or unset
    // means auto-pick the first multilingual voice
    char* readAloudMultilingualVoice;
    // color used to highlight the text being read aloud (text-to-speech
    // and EPUB 3 narration)
    char* readAloudHighlightColor;
    ParsedColor readAloudHighlightColorParsed;
    // if true, the view scrolls to keep the text being read aloud visible
    bool readAloudAutoFollow;
    // if true, EPUB 3 books with media overlays are read aloud with the
    // publisher's recorded narration instead of text-to-speech
    bool narrationUseBookAudio;
    // if true, EPUB 3 narration highlights the current phrase with the
    // book's own media:active-class color when it defines one
    bool narrationUseBookHighlightColor;
    // playback speed of EPUB 3 narration audio; 1.0 is normal speed
    float narrationSpeed;
    // passwords to try when opening a password protected document
    Vec<char*>* defaultPasswords;
    // ISO code of the current UI language
    char* uiLanguage;
    // version for which the update prompt is temporarily snoozed
    char* versionToSkip;
    // default state of new windows (same as the last closed)
    int windowState;
    // default position (can be on any monitor)
    Rect windowPos;
    // position/size of the floating find window (see SearchUIFloating)
    Rect searchUIWindowPos;
    // information about opened files (in most recently used order)
    Vec<FileState*>* fileStates;
    // state of the last session, usage depends on RestoreSession
    Vec<SessionData*>* sessionData;
    // a list of paths for files to be reopened at the next start or the
    // string "SessionData" if this data is saved in SessionData (needed
    // for auto-updating)
    Vec<char*>* reopenOnce;
    // timestamp of the last update check
    FILETIME timeOfLastUpdateCheck;
    // timestamp when an update version was snoozed
    FILETIME timeOfUpdateCheckSnooze;
    // week count since 2011-01-01 needed to "age" openCount values in file
    // history
    int openCountWeek;
    // modification time of the preferences file when it was last read
    FILETIME lastPrefUpdate;
    // value of DefaultDisplayMode for internal usage
    DisplayMode defaultDisplayModeEnum;
    // value of DefaultZoom for internal usage
    float defaultZoomFloat;
    // position of the document properties window
    Point propWinPos;
};
// for parsing themes
struct Themes {
    // color themes
    Vec<Theme*>* themes;
};

#ifdef INCLUDE_SETTINGSSTRUCTS_METADATA

static const FieldInfo gWindowMarginFields[] = {
    {offsetof(WindowMargin, top), SettingType::Int, 2, nullptr},
    {offsetof(WindowMargin, right), SettingType::Int, 4, nullptr},
    {offsetof(WindowMargin, bottom), SettingType::Int, 2, nullptr},
    {offsetof(WindowMargin, left), SettingType::Int, 4, nullptr},
};
static const StructInfo gWindowMarginInfo = {sizeof(WindowMargin), 4, gWindowMarginFields, "Top\0Right\0Bottom\0Left"};

static const FieldInfo gSizeFields[] = {
    {offsetof(Size, dx), SettingType::Int, 4, nullptr},
    {offsetof(Size, dy), SettingType::Int, 4, nullptr},
};
static const StructInfo gSizeInfo = {sizeof(Size), 2, gSizeFields, "Dx\0Dy"};

static const FieldInfo gFixedPageUIFields[] = {
    {offsetof(FixedPageUI, textColor), SettingType::Color, (intptr_t)"#000000", "文字颜色"},
    {offsetof(FixedPageUI, backgroundColor), SettingType::Color, (intptr_t)"#ffffff", "页面底色"},
    {offsetof(FixedPageUI, selectionColor), SettingType::Color, (intptr_t)"#99c1da", "选中高亮色"},
    {offsetof(FixedPageUI, selectionHeightRatio), SettingType::Float, (intptr_t)"1",
     "选中文字背景高度比例 0.5-1.5，越小越薄"},
    {offsetof(FixedPageUI, windowMargin), SettingType::Compact, (intptr_t)&gWindowMarginInfo, "页边距 上 右 下 左"},
    {offsetof(FixedPageUI, pageSpacing), SettingType::Compact, (intptr_t)&gSizeInfo, "页面间距 横 纵"},
    {offsetof(FixedPageUI, gradientColors), SettingType::ColorArray, 0, nullptr},
    {offsetof(FixedPageUI, invertColors), SettingType::Bool, false, "全局反色"},
    {offsetof(FixedPageUI, windowBgCol), SettingType::Color, (intptr_t)"", "PDF 画布背景色"},
    {offsetof(FixedPageUI, findMatchColor), SettingType::Color, (intptr_t)"#ffff00", "查找匹配高亮色"},
    {offsetof(FixedPageUI, joinSplitPdfImages), SettingType::Bool, true, nullptr},
};
static const StructInfo gFixedPageUIInfo = {
    sizeof(FixedPageUI), 11, gFixedPageUIFields,
    "TextColor\0BackgroundColor\0SelectionColor\0SelectionHeightRatio\0WindowMargin\0PageSpacing\0GradientColors\0Inver"
    "tColors\0WindowBgCol\0FindMatchColor\0JoinSplitPdfImages"};

static const FieldInfo gEBookUIFields[] = {
    {offsetof(EBookUI, fontSize), SettingType::Float, (intptr_t)"0",
     "6–26 之间的数字，单位是磅（pt）；0=内置默认；超出范围无效"},
    {offsetof(EBookUI, fontFamily), SettingType::String, (intptr_t)"Literata", "电子书西文/默认衬线字体"},
    {offsetof(EBookUI, cjkFontFamily), SettingType::String, (intptr_t)"Source Han Serif SC", "电子书中文正文字体"},
    {offsetof(EBookUI, cjkFontFile), SettingType::String, 0, nullptr},
    {offsetof(EBookUI, layoutDx), SettingType::Float, (intptr_t)"0", "页面宽度 pt"},
    {offsetof(EBookUI, layoutDy), SettingType::Float, (intptr_t)"0", "页面高度 pt"},
    {offsetof(EBookUI, ignoreDocumentCSS), SettingType::Bool, false, "忽略文档 CSS"},
    {offsetof(EBookUI, customCSS), SettingType::String, 0, "自定义 CSS"},
    {offsetof(EBookUI, epubProgressiveLoad), SettingType::Bool, true, "EPUB 渐进加载"},
    {offsetof(EBookUI, epubPerfLog), SettingType::Bool, false, "EPUB 性能日志"},
    {offsetof(EBookUI, windowBgCol), SettingType::Color, (intptr_t)"", "电子书画布背景色"},
};
static const StructInfo gEBookUIInfo = {sizeof(EBookUI), 11, gEBookUIFields,
                                        "FontSize\0FontFamily\0CjkFontFamily\0CjkFontFile\0LayoutDx\0LayoutDy\0IgnoreDo"
                                        "cumentCSS\0CustomCSS\0EpubProgressiveLoad\0EpubPerfLog\0WindowBgCol"};

static const FieldInfo gWindowMargin_1_Fields[] = {
    {offsetof(WindowMargin, top), SettingType::Int, 0, nullptr},
    {offsetof(WindowMargin, right), SettingType::Int, 0, nullptr},
    {offsetof(WindowMargin, bottom), SettingType::Int, 0, nullptr},
    {offsetof(WindowMargin, left), SettingType::Int, 0, nullptr},
};
static const StructInfo gWindowMargin_1_Info = {sizeof(WindowMargin), 4, gWindowMargin_1_Fields,
                                                "Top\0Right\0Bottom\0Left"};

static const FieldInfo gSize_1_Fields[] = {
    {offsetof(Size, dx), SettingType::Int, 4, nullptr},
    {offsetof(Size, dy), SettingType::Int, 4, nullptr},
};
static const StructInfo gSize_1_Info = {sizeof(Size), 2, gSize_1_Fields, "Dx\0Dy"};

static const FieldInfo gComicBookUIFields[] = {
    {offsetof(ComicBookUI, windowMargin), SettingType::Compact, (intptr_t)&gWindowMargin_1_Info, "漫画页边距"},
    {offsetof(ComicBookUI, pageSpacing), SettingType::Compact, (intptr_t)&gSize_1_Info, "漫画分页间距"},
    {offsetof(ComicBookUI, cbxMangaMode), SettingType::Bool, false, "日式右向左阅读"},
    {offsetof(ComicBookUI, windowBgCol), SettingType::Color, (intptr_t)"", "漫画画布背景色"},
};
static const StructInfo gComicBookUIInfo = {sizeof(ComicBookUI), 4, gComicBookUIFields,
                                            "WindowMargin\0PageSpacing\0CbxMangaMode\0WindowBgCol"};

static const FieldInfo gImageUIFields[] = {
    {offsetof(ImageUI, windowBgCol), SettingType::Color, (intptr_t)"", "图片画布背景色"},
    {offsetof(ImageUI, defaultZoom), SettingType::String, (intptr_t)"shrink to fit", "打开图片默认缩放"},
};
static const StructInfo gImageUIInfo = {sizeof(ImageUI), 2, gImageUIFields, "WindowBgCol\0DefaultZoom"};

static const FieldInfo gChmUIFields[] = {
    {offsetof(ChmUI, useFixedPageUI), SettingType::Bool, false, "true=使用 PDF 式布局"},
};
static const StructInfo gChmUIInfo = {sizeof(ChmUI), 1, gChmUIFields, "UseFixedPageUI"};

static const FieldInfo gAnnotationsFields[] = {
    {offsetof(Annotations, highlightColor), SettingType::Color, (intptr_t)"#ffff00", "高亮颜色"},
    {offsetof(Annotations, underlineColor), SettingType::Color, (intptr_t)"#00ff00", "下划线颜色"},
    {offsetof(Annotations, squigglyColor), SettingType::Color, (intptr_t)"#ff00ff", "波浪线颜色"},
    {offsetof(Annotations, strikeOutColor), SettingType::Color, (intptr_t)"#ff0000", "删除线颜色"},
    {offsetof(Annotations, freeTextColor), SettingType::Color, (intptr_t)"", "文本批注文字色"},
    {offsetof(Annotations, freeTextBackgroundColor), SettingType::Color, (intptr_t)"", "文本批注背景色"},
    {offsetof(Annotations, freeTextOpacity), SettingType::Int, 100, "批注不透明度 0-100"},
    {offsetof(Annotations, freeTextSize), SettingType::Int, 12, "文本批注字号"},
    {offsetof(Annotations, freeTextBorderWidth), SettingType::Int, 1, "批注边框粗细"},
    {offsetof(Annotations, textIconColor), SettingType::Color, (intptr_t)"", "批注图标颜色"},
    {offsetof(Annotations, textIconType), SettingType::String, (intptr_t)"", "批注图标类型"},
    {offsetof(Annotations, defaultAuthor), SettingType::String, (intptr_t)"", "新建注释默认作者"},
    {offsetof(Annotations, selectionToolbar), SettingType::Bool, true, "选中文字后显示划词工具栏"},
};
static const StructInfo gAnnotationsInfo = {
    sizeof(Annotations), 13, gAnnotationsFields,
    "HighlightColor\0UnderlineColor\0SquigglyColor\0StrikeOutColor\0FreeTextColor\0FreeTextBackgroundColor\0FreeTextOpa"
    "city\0FreeTextSize\0FreeTextBorderWidth\0TextIconColor\0TextIconType\0DefaultAuthor\0SelectionToolbar"};

static const FieldInfo gExternalViewerFields[] = {
    {offsetof(ExternalViewer, commandLine), SettingType::String, 0, "外部程序命令行"},
    {offsetof(ExternalViewer, name), SettingType::String, 0, "菜单显示名称"},
    {offsetof(ExternalViewer, filter), SettingType::String, 0, "文件类型过滤"},
    {offsetof(ExternalViewer, key), SettingType::String, 0, "快捷键"},
    {offsetof(ExternalViewer, toolbarText), SettingType::String, 0, "工具栏文字"},
};
static const StructInfo gExternalViewerInfo = {sizeof(ExternalViewer), 5, gExternalViewerFields,
                                               "CommandLine\0Name\0Filter\0Key\0ToolbarText"};

static const FieldInfo gForwardSearchFields[] = {
    {offsetof(ForwardSearch, highlightOffset), SettingType::Int, 0, "高亮条左边距"},
    {offsetof(ForwardSearch, highlightWidth), SettingType::Int, 15, "高亮条宽度"},
    {offsetof(ForwardSearch, highlightColor), SettingType::Color, (intptr_t)"#6581ff", "高亮颜色"},
    {offsetof(ForwardSearch, highlightPermanent), SettingType::Bool, false, "高亮保持到下次点击"},
};
static const StructInfo gForwardSearchInfo = {sizeof(ForwardSearch), 4, gForwardSearchFields,
                                              "HighlightOffset\0HighlightWidth\0HighlightColor\0HighlightPermanent"};

static const FieldInfo gPrinterDefaultsFields[] = {
    {offsetof(PrinterDefaults, printScale), SettingType::String, (intptr_t)"shrink", "打印缩放 shrink/fit/none"},
};
static const StructInfo gPrinterDefaultsInfo = {sizeof(PrinterDefaults), 1, gPrinterDefaultsFields, "PrintScale"};

static const FieldInfo gFullscreenFields[] = {
    {offsetof(Fullscreen, showToolbar), SettingType::Bool, false, "全屏时显示工具栏"},
    {offsetof(Fullscreen, showMenubar), SettingType::Bool, false, "全屏时显示菜单栏"},
};
static const StructInfo gFullscreenInfo = {sizeof(Fullscreen), 2, gFullscreenFields, "ShowToolbar\0ShowMenubar"};

static const FieldInfo gSelectionHandlerFields[] = {
    {offsetof(SelectionHandler, url), SettingType::String, 0, "搜索 URL"},
    {offsetof(SelectionHandler, name), SettingType::String, 0, "菜单名称"},
    {offsetof(SelectionHandler, key), SettingType::String, 0, "快捷键"},
};
static const StructInfo gSelectionHandlerInfo = {sizeof(SelectionHandler), 3, gSelectionHandlerFields,
                                                 "URL\0Name\0Key"};

static const FieldInfo gShortcutFields[] = {
    {offsetof(Shortcut, cmd), SettingType::String, (intptr_t)"", "命令"},
    {offsetof(Shortcut, key), SettingType::String, (intptr_t)"", "快捷键"},
    {offsetof(Shortcut, name), SettingType::String, 0, "命令面板名称"},
    {offsetof(Shortcut, toolbarText), SettingType::String, 0, "工具栏文字"},
};
static const StructInfo gShortcutInfo = {sizeof(Shortcut), 4, gShortcutFields, "Cmd\0Key\0Name\0ToolbarText"};

static const FieldInfo gThemeFields[] = {
    {offsetof(Theme, name), SettingType::String, (intptr_t)"", "主题名称"},
    {offsetof(Theme, textColor), SettingType::Color, (intptr_t)"", "文字颜色"},
    {offsetof(Theme, backgroundColor), SettingType::Color, (intptr_t)"", "背景颜色"},
    {offsetof(Theme, controlBackgroundColor), SettingType::Color, (intptr_t)"", "控件背景色"},
    {offsetof(Theme, linkColor), SettingType::Color, (intptr_t)"", "链接颜色"},
    {offsetof(Theme, colorizeControls), SettingType::Bool, false, "着色 Windows 控件"},
};
static const StructInfo gThemeInfo = {
    sizeof(Theme), 6, gThemeFields,
    "Name\0TextColor\0BackgroundColor\0ControlBackgroundColor\0LinkColor\0ColorizeControls"};

static const FieldInfo gTabFileFields[] = {
    {offsetof(TabFile, path), SettingType::String, (intptr_t)"", nullptr},
};
static const StructInfo gTabFileInfo = {sizeof(TabFile), 1, gTabFileFields, "Path"};

static const FieldInfo gTabGroupFields[] = {
    {offsetof(TabGroup, name), SettingType::String, (intptr_t)"", "分组名称"},
    {offsetof(TabGroup, tabFiles), SettingType::Array, (intptr_t)&gTabFileInfo, nullptr},
};
static const StructInfo gTabGroupInfo = {sizeof(TabGroup), 2, gTabGroupFields, "Name\0TabFiles"};

static const FieldInfo gRectFields[] = {
    {offsetof(Rect, x), SettingType::Int, 0, nullptr},
    {offsetof(Rect, y), SettingType::Int, 0, nullptr},
    {offsetof(Rect, dx), SettingType::Int, 0, nullptr},
    {offsetof(Rect, dy), SettingType::Int, 0, nullptr},
};
static const StructInfo gRectInfo = {sizeof(Rect), 4, gRectFields, "X\0Y\0Dx\0Dy"};

static const FieldInfo gRect_1_Fields[] = {
    {offsetof(Rect, x), SettingType::Int, 0, nullptr},
    {offsetof(Rect, y), SettingType::Int, 0, nullptr},
    {offsetof(Rect, dx), SettingType::Int, 0, nullptr},
    {offsetof(Rect, dy), SettingType::Int, 0, nullptr},
};
static const StructInfo gRect_1_Info = {sizeof(Rect), 4, gRect_1_Fields, "X\0Y\0Dx\0Dy"};

static const FieldInfo gFavoriteFields[] = {
    {offsetof(Favorite, name), SettingType::String, 0, nullptr},
    {offsetof(Favorite, pageNo), SettingType::Int, 0, nullptr},
    {offsetof(Favorite, pageLabel), SettingType::String, 0, nullptr},
    {offsetof(Favorite, addedSeq), SettingType::Int, 0, nullptr},
};
static const StructInfo gFavoriteInfo = {sizeof(Favorite), 4, gFavoriteFields, "Name\0PageNo\0PageLabel\0AddedSeq"};

static const FieldInfo gPointFFields[] = {
    {offsetof(PointF, x), SettingType::Float, (intptr_t)"0", nullptr},
    {offsetof(PointF, y), SettingType::Float, (intptr_t)"0", nullptr},
};
static const StructInfo gPointFInfo = {sizeof(PointF), 2, gPointFFields, "X\0Y"};

static const FieldInfo gRect_2_Fields[] = {
    {offsetof(Rect, x), SettingType::Int, 0, nullptr},
    {offsetof(Rect, y), SettingType::Int, 0, nullptr},
    {offsetof(Rect, dx), SettingType::Int, 0, nullptr},
    {offsetof(Rect, dy), SettingType::Int, 0, nullptr},
};
static const StructInfo gRect_2_Info = {sizeof(Rect), 4, gRect_2_Fields, "X\0Y\0Dx\0Dy"};

static const FieldInfo gFileStateFields[] = {
    {offsetof(FileState, filePath), SettingType::String, 0, nullptr},
    {offsetof(FileState, favorites), SettingType::Array, (intptr_t)&gFavoriteInfo, nullptr},
    {offsetof(FileState, isPinned), SettingType::Bool, false, nullptr},
    {offsetof(FileState, isMissing), SettingType::Bool, false, nullptr},
    {offsetof(FileState, openCount), SettingType::Int, 0, nullptr},
    {offsetof(FileState, decryptionKey), SettingType::String, 0, nullptr},
    {offsetof(FileState, useDefaultState), SettingType::Bool, false, nullptr},
    {offsetof(FileState, displayMode), SettingType::String, (intptr_t)"automatic", nullptr},
    {offsetof(FileState, scrollPos), SettingType::Compact, (intptr_t)&gPointFInfo, nullptr},
    {offsetof(FileState, pageNo), SettingType::Int, 1, nullptr},
    {offsetof(FileState, zoom), SettingType::String, (intptr_t)"fit page", nullptr},
    {offsetof(FileState, rotation), SettingType::Int, 0, nullptr},
    {offsetof(FileState, windowState), SettingType::Int, 0, nullptr},
    {offsetof(FileState, windowPos), SettingType::Compact, (intptr_t)&gRect_2_Info, nullptr},
    {offsetof(FileState, showToc), SettingType::Bool, true, nullptr},
    {offsetof(FileState, sidebarView), SettingType::String, (intptr_t)"bookmarks", nullptr},
    {offsetof(FileState, sidebarDx), SettingType::Int, 0, nullptr},
    {offsetof(FileState, displayR2L), SettingType::Bool, false, nullptr},
    {offsetof(FileState, bgCol), SettingType::Color, (intptr_t)"", nullptr},
    {offsetof(FileState, tabCol), SettingType::Color, (intptr_t)"", nullptr},
    {offsetof(FileState, displayFilterBrightness), SettingType::Int, 0, "该文档页面亮度（-100..100，0=预设基线）"},
    {offsetof(FileState, displayFilterContrast), SettingType::Int, 0, "该文档页面对比度（-100..100，0=预设基线）"},
    {offsetof(FileState, displayFilterSharpness), SettingType::Int, 0, "该文档页面锐度（0..100，0=预设基线）"},
    {offsetof(FileState, displayFilterMode), SettingType::Int, 0,
     "该文档显示增强模式（0=关闭，1=旧版，2=阅读，3=扫描件）"},
    {offsetof(FileState, autoOcrOn), SettingType::Bool, false, nullptr},
    {offsetof(FileState, reparseIdx), SettingType::Int, 0, nullptr},
    {offsetof(FileState, tocState), SettingType::IntArray, 0, nullptr},
};
static StructInfo gFileStateInfo = {
    sizeof(FileState), 27, gFileStateFields,
    "FilePath\0Favorites\0IsPinned\0IsMissing\0OpenCount\0DecryptionKey\0UseDefaultState\0DisplayMode\0ScrollPos\0PageN"
    "o\0Zoom\0Rotation\0WindowState\0WindowPos\0ShowToc\0SidebarView\0SidebarDx\0DisplayR2L\0BgCol\0TabCol\0DisplayFilt"
    "erBrightness\0DisplayFilterContrast\0DisplayFilterSharpness\0DisplayFilterMode\0AutoOcrOn\0ReparseIdx\0TocState"};

static const FieldInfo gPointF_1_Fields[] = {
    {offsetof(PointF, x), SettingType::Float, (intptr_t)"0", nullptr},
    {offsetof(PointF, y), SettingType::Float, (intptr_t)"0", nullptr},
};
static const StructInfo gPointF_1_Info = {sizeof(PointF), 2, gPointF_1_Fields, "X\0Y"};

static const FieldInfo gTabStateFields[] = {
    {offsetof(TabState, filePath), SettingType::String, 0, nullptr},
    {offsetof(TabState, displayMode), SettingType::String, (intptr_t)"automatic", nullptr},
    {offsetof(TabState, pageNo), SettingType::Int, 1, nullptr},
    {offsetof(TabState, zoom), SettingType::String, (intptr_t)"fit page", nullptr},
    {offsetof(TabState, rotation), SettingType::Int, 0, nullptr},
    {offsetof(TabState, scrollPos), SettingType::Compact, (intptr_t)&gPointF_1_Info, nullptr},
    {offsetof(TabState, showToc), SettingType::Bool, true, nullptr},
    {offsetof(TabState, tocState), SettingType::IntArray, 0, nullptr},
};
static const StructInfo gTabStateInfo = {sizeof(TabState), 8, gTabStateFields,
                                         "FilePath\0DisplayMode\0PageNo\0Zoom\0Rotation\0ScrollPos\0ShowToc\0TocState"};

static const FieldInfo gRect_3_Fields[] = {
    {offsetof(Rect, x), SettingType::Int, 0, nullptr},
    {offsetof(Rect, y), SettingType::Int, 0, nullptr},
    {offsetof(Rect, dx), SettingType::Int, 0, nullptr},
    {offsetof(Rect, dy), SettingType::Int, 0, nullptr},
};
static const StructInfo gRect_3_Info = {sizeof(Rect), 4, gRect_3_Fields, "X\0Y\0Dx\0Dy"};

static const FieldInfo gSessionDataFields[] = {
    {offsetof(SessionData, tabStates), SettingType::Array, (intptr_t)&gTabStateInfo, nullptr},
    {offsetof(SessionData, tabIndex), SettingType::Int, 1, nullptr},
    {offsetof(SessionData, windowState), SettingType::Int, 0, nullptr},
    {offsetof(SessionData, windowPos), SettingType::Compact, (intptr_t)&gRect_3_Info, nullptr},
    {offsetof(SessionData, sidebarDx), SettingType::Int, 0, nullptr},
};
static const StructInfo gSessionDataInfo = {sizeof(SessionData), 5, gSessionDataFields,
                                            "TabStates\0TabIndex\0WindowState\0WindowPos\0SidebarDx"};

static const FieldInfo gFILETIMEFields[] = {
    {offsetof(FILETIME, dwHighDateTime), SettingType::Int, 0, nullptr},
    {offsetof(FILETIME, dwLowDateTime), SettingType::Int, 0, nullptr},
};
static const StructInfo gFILETIMEInfo = {sizeof(FILETIME), 2, gFILETIMEFields, "DwHighDateTime\0DwLowDateTime"};

static const FieldInfo gFILETIME_1_Fields[] = {
    {offsetof(FILETIME, dwHighDateTime), SettingType::Int, 0, nullptr},
    {offsetof(FILETIME, dwLowDateTime), SettingType::Int, 0, nullptr},
};
static const StructInfo gFILETIME_1_Info = {sizeof(FILETIME), 2, gFILETIME_1_Fields, "DwHighDateTime\0DwLowDateTime"};

static const FieldInfo gPointFields[] = {
    {offsetof(Point, x), SettingType::Int, 0, nullptr},
    {offsetof(Point, y), SettingType::Int, 0, nullptr},
};
static const StructInfo gPointInfo = {sizeof(Point), 2, gPointFields, "X\0Y"};

static const FieldInfo gGlobalPrefsFields[] = {
    {(size_t)-1, SettingType::Comment,
     (intptr_t)"For documentation, see https://www.sumatrapdfreader.org/settings/settings3-7-37.html",
     "For documentation, see https://www.sumatrapdfreader.org/settings/settings3-7-37.html"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, checkForUpdates), SettingType::Bool, true, "是否每天自动检测新版本"},
    {offsetof(GlobalPrefs, customScreenDPI), SettingType::Int, 0, "自定义主屏幕 DPI；0=跟随系统"},
    {offsetof(GlobalPrefs, defaultDisplayMode), SettingType::String, (intptr_t)"automatic", "默认页面布局"},
    {offsetof(GlobalPrefs, defaultZoom), SettingType::String, (intptr_t)"fit page", "默认缩放"},
    {offsetof(GlobalPrefs, enableTeXEnhancements), SettingType::Bool, false, "显示 LaTeX SyncTeX 反向搜索命令行"},
    {offsetof(GlobalPrefs, escToExit), SettingType::Bool, false, "true=按 Esc 直接关闭窗口"},
    {offsetof(GlobalPrefs, fullPathInTitle), SettingType::Bool, false, "标题栏显示完整路径"},
    {offsetof(GlobalPrefs, inverseSearchCmdLine), SettingType::String, 0, "LaTeX 反向搜索命令行"},
    {offsetof(GlobalPrefs, lazyLoading), SettingType::Bool, false, "恢复会话时延迟加载未选中标签页"},
    {offsetof(GlobalPrefs, mainWindowBackground), SettingType::Color, (intptr_t)"#80fff200",
     "文档外侧空白区域底色 #AARRGGBB"},
    {offsetof(GlobalPrefs, noHomeTab), SettingType::Bool, false, "标签模式下不显示首页标签"},
    {offsetof(GlobalPrefs, homePageSortByFrequentlyRead), SettingType::Bool, false, "首页按打开次数排序"},
    {offsetof(GlobalPrefs, homePageViewMode), SettingType::String, (intptr_t)"thumbnails", "首页视图 thumbnails/list"},
    {offsetof(GlobalPrefs, homePageThumbnailDx), SettingType::Int, 212,
     "首页缩略图首选宽度（像素），会略微伸缩铺满窗口；列表视图不受影响；有效范围 160-280"},
    {offsetof(GlobalPrefs, reloadModifiedDocuments), SettingType::Bool, true, "外部修改后自动重载"},
    {offsetof(GlobalPrefs, rememberOpenedFiles), SettingType::Bool, true, "记录打开过的文件"},
    {offsetof(GlobalPrefs, rememberStatePerDocument), SettingType::Bool, true, "为每个文档单独保存阅读进度"},
    {offsetof(GlobalPrefs, restoreSession), SettingType::Bool, true, "启动时恢复上次会话"},
    {offsetof(GlobalPrefs, reuseInstance), SettingType::Bool, true, "新文件在已有窗口打开"},
    {offsetof(GlobalPrefs, showMenubar), SettingType::Bool, true, "非标签模式下显示菜单栏"},
    {offsetof(GlobalPrefs, showMenubarWithTabs), SettingType::Bool, false, "标签模式下显示菜单栏"},
    {offsetof(GlobalPrefs, showTips), SettingType::Bool, false, "在首页显示使用技巧"},
    {offsetof(GlobalPrefs, customColors), SettingType::String, 0, "背景色选择器自定义颜色"},
    {offsetof(GlobalPrefs, showToolbar), SettingType::Bool, true, "显示顶部工具栏"},
    {offsetof(GlobalPrefs, showAnnotToolbarButtons), SettingType::Bool, true,
     "工具栏显示矩形/椭圆/直线/画笔快捷标注按钮"},
    {offsetof(GlobalPrefs, searchUIFloating), SettingType::Bool, false, "true=悬浮搜索窗口"},
    {offsetof(GlobalPrefs, offlineDictionaryPath), SettingType::String, 0, "离线词典目录"},
    {offsetof(GlobalPrefs, enableDoubleClickWordLookup), SettingType::Bool, true, "双击查离线词典"},
    {offsetof(GlobalPrefs, autoOcrScanPages), SettingType::Bool, true,
     "自动识别无文字层的扫描页，便于选择和搜索；模型在 {exedir}/ocr/"},
    {offsetof(GlobalPrefs, ocrAutoSave), SettingType::Bool, false, "全文识别或提取目录完成后覆盖保存当前 PDF"},
    {offsetof(GlobalPrefs, ocrDeskew), SettingType::Bool, true, nullptr},
    {offsetof(GlobalPrefs, ocrFullDocumentMode), SettingType::String, (intptr_t)"fast",
     "全文识别模式 fast=极速 accurate=高精度；自动 OCR 使用极速，框选/当前页使用高精度"},
    {offsetof(GlobalPrefs, ocrCopyMerged), SettingType::Bool, true, nullptr},
    {offsetof(GlobalPrefs, extractPdfTocMode), SettingType::String, (intptr_t)"standard",
     "智能提取目录详细程度 conservative/standard/detailed"},
    {offsetof(GlobalPrefs, aiChatProvider), SettingType::String, (intptr_t)"doubao",
     "Ask AI 提供商 doubao/deepseek/chatgpt"},
    {offsetof(GlobalPrefs, aiTocApiBaseUrl), SettingType::String, (intptr_t)"", nullptr},
    {offsetof(GlobalPrefs, aiTocApiKey), SettingType::String, (intptr_t)"", nullptr},
    {offsetof(GlobalPrefs, aiTocApiModel), SettingType::String, (intptr_t)"", nullptr},
    {offsetof(GlobalPrefs, aiTocApiProfiles), SettingType::String, (intptr_t)"", nullptr},
    {offsetof(GlobalPrefs, aiTocApiConcurrency), SettingType::Int, 4, nullptr},
    {offsetof(GlobalPrefs, aiChatUseDeepSeekInsteadOfDoubao), SettingType::Bool, false, "已弃用，请用 AiChatProvider"},
    {offsetof(GlobalPrefs, enableAskAI), SettingType::Bool, true, "显示 Ask AI 入口"},
    {offsetof(GlobalPrefs, enableInlineTranslate), SettingType::Bool, true, "显示划词翻译入口"},
    {offsetof(GlobalPrefs, translateVolcAccessKey), SettingType::String, (intptr_t)"",
     "火山翻译 Access Key（可 DPAPI 加密）"},
    {offsetof(GlobalPrefs, translateVolcSecretKey), SettingType::String, (intptr_t)"",
     "火山翻译 Secret Key（可 DPAPI 加密）"},
    {offsetof(GlobalPrefs, translateTargetMode), SettingType::String, (intptr_t)"auto",
     "划词翻译目标语 auto/ui/zh/zh-Hant/en/ja/ko/…"},
    {offsetof(GlobalPrefs, showFavorites), SettingType::Bool, false, "默认显示收藏侧边栏"},
    {offsetof(GlobalPrefs, showToc), SettingType::Bool, true, "默认显示目录侧边栏"},
    {offsetof(GlobalPrefs, showLinks), SettingType::Bool, false, "为链接绘制蓝色边框"},
    {offsetof(GlobalPrefs, showStartPage), SettingType::Bool, true, "无文档时显示最近文件"},
    {offsetof(GlobalPrefs, sidebarDx), SettingType::Int, 0, "侧边栏宽度，0=默认"},
    {offsetof(GlobalPrefs, scrollbars), SettingType::String, (intptr_t)"windows",
     "滚动条 windows/smart/overlay/hidden"},
    {offsetof(GlobalPrefs, scrollbarInSinglePage), SettingType::Bool, false, "单页模式显示滚动条"},
    {offsetof(GlobalPrefs, smoothScroll), SettingType::Bool, false, "平滑滚动"},
    {offsetof(GlobalPrefs, fastScrollOverScrollbar), SettingType::Bool, false, "滚轮在滚动条区域时半页滚动"},
    {offsetof(GlobalPrefs, preventSleepInFullscreen), SettingType::Bool, true, "全屏/演示时阻止休眠"},
    {offsetof(GlobalPrefs, tabWidth), SettingType::Int, 300, "单个标签最大宽度"},
    {offsetof(GlobalPrefs, tabFontSize), SettingType::Int, 0, "标签栏字号（0=自动）"},
    {offsetof(GlobalPrefs, tabBarHeight), SettingType::Int, 0, "标签栏高度（0=自动）"},
    {offsetof(GlobalPrefs, theme), SettingType::String, (intptr_t)"", "当前主题"},
    {offsetof(GlobalPrefs, lastDarkTheme), SettingType::String, (intptr_t)"Dark-Dracula", "切换到深色模式时的主题"},
    {offsetof(GlobalPrefs, lastLightTheme), SettingType::String, (intptr_t)"Light-Warm", "切换到浅色模式时的主题"},
    {offsetof(GlobalPrefs, documentColorMode), SettingType::String, (intptr_t)"theme",
     "文档颜色模式 original/theme（原稿/匹配主题）"},
    {offsetof(GlobalPrefs, documentImageDarkStrategy), SettingType::String, (intptr_t)"auto", nullptr},
    {offsetof(GlobalPrefs, tocDy), SettingType::Int, 0, "目录区高度（与收藏同显时）"},
    {offsetof(GlobalPrefs, toolbarSize), SettingType::Int, 18, "工具栏高度"},
    {offsetof(GlobalPrefs, treeFontName), SettingType::String, (intptr_t)"automatic", "目录/收藏树字体"},
    {offsetof(GlobalPrefs, treeFontSize), SettingType::Int, 0, "目录/收藏树字号"},
    {offsetof(GlobalPrefs, treeWrapLabels), SettingType::Bool, false,
     "true=书签/收藏长标题多行换行；false=单行省略+悬停显示全文"},
    {offsetof(GlobalPrefs, uIFontSize), SettingType::Int, 0, "界面字体大小"},
    {offsetof(GlobalPrefs, disableAntiAlias), SettingType::Bool, false, "关闭 PDF 抗锯齿"},
    {offsetof(GlobalPrefs, engineeringDrawingEnhance), SettingType::String, (intptr_t)"auto",
     "工程图纸增强 off/auto/on"},
    {offsetof(GlobalPrefs, useSysColors), SettingType::Bool, false, "使用 Windows 系统主题色"},
    {offsetof(GlobalPrefs, useTabs), SettingType::Bool, true, "启用标签页"},
    {offsetof(GlobalPrefs, tabsMru), SettingType::Bool, false, "Ctrl+Tab 按最近使用排序"},
    {offsetof(GlobalPrefs, zoomLevels), SettingType::FloatArray, (intptr_t)"", "自定义缩放档位"},
    {offsetof(GlobalPrefs, zoomIncrement), SettingType::Float, (intptr_t)"0", "滚轮缩放步长"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, fixedPageUI), SettingType::Struct, (intptr_t)&gFixedPageUIInfo, "PDF/XPS/DjVu 界面"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, eBookUI), SettingType::Struct, (intptr_t)&gEBookUIInfo, "EPUB/MOBI 电子书界面"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, comicBookUI), SettingType::Struct, (intptr_t)&gComicBookUIInfo, "CBZ/CBR 漫画界面"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, imageUI), SettingType::Struct, (intptr_t)&gImageUIInfo, "图片文件界面"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, chmUI), SettingType::Struct, (intptr_t)&gChmUIInfo, "CHM 帮助文档界面"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, annotations), SettingType::Struct, (intptr_t)&gAnnotationsInfo, "注释默认样式"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, externalViewers), SettingType::Array, (intptr_t)&gExternalViewerInfo, "外部程序打开方式"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, forwardSearch), SettingType::Struct, (intptr_t)&gForwardSearchInfo, "SyncTeX 正向搜索高亮"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, printerDefaults), SettingType::Struct, (intptr_t)&gPrinterDefaultsInfo, "打印默认参数"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, fullscreen), SettingType::Struct, (intptr_t)&gFullscreenInfo, "全屏模式设置"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, selectionHandlers), SettingType::Array, (intptr_t)&gSelectionHandlerInfo,
     "选中文字自定义搜索"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, shortcuts), SettingType::Array, (intptr_t)&gShortcutInfo, "自定义快捷键"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, themes), SettingType::Array, (intptr_t)&gThemeInfo, "自定义主题"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, tabGroups), SettingType::Array, (intptr_t)&gTabGroupInfo, "标签分组"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {offsetof(GlobalPrefs, readAloudVoiceId), SettingType::String, 0, "朗读语音 ID"},
    {offsetof(GlobalPrefs, readAloudSpeakingRate), SettingType::Float, (intptr_t)"1", "朗读语速（旧）"},
    {offsetof(GlobalPrefs, readAloudSpeakingRateZh), SettingType::Float, (intptr_t)"1", "中文朗读语速"},
    {offsetof(GlobalPrefs, readAloudSpeakingRateEn), SettingType::Float, (intptr_t)"1", "英文朗读语速"},
    {offsetof(GlobalPrefs, readAloudSmartVoiceZh), SettingType::String, 0, "本地智能中文语音"},
    {offsetof(GlobalPrefs, readAloudSmartVoiceEn), SettingType::String, 0, "本地智能英文语音"},
    {offsetof(GlobalPrefs, readAloudSmartOnlineVoiceZh), SettingType::String, 0, "在线智能中文语音"},
    {offsetof(GlobalPrefs, readAloudSmartOnlineVoiceEn), SettingType::String, 0, "在线智能英文语音"},
    {offsetof(GlobalPrefs, readAloudMultilingualVoice), SettingType::String, 0, "在线多语言语音"},
    {offsetof(GlobalPrefs, readAloudHighlightColor), SettingType::Color, (intptr_t)"#ffff00", "朗读高亮色"},
    {offsetof(GlobalPrefs, readAloudAutoFollow), SettingType::Bool, true, "朗读时自动跟随"},
    {offsetof(GlobalPrefs, narrationUseBookAudio), SettingType::Bool, true, "有声书使用书内录音"},
    {offsetof(GlobalPrefs, narrationUseBookHighlightColor), SettingType::Bool, true, "有声书使用书内高亮色"},
    {offsetof(GlobalPrefs, narrationSpeed), SettingType::Float, (intptr_t)"1", "有声书播放倍速"},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {(size_t)-1, SettingType::Comment, (intptr_t)"You're not expected to change those manually",
     "You're not expected to change those manually"},
    {offsetof(GlobalPrefs, defaultPasswords), SettingType::StringArray, 0, nullptr},
    {offsetof(GlobalPrefs, uiLanguage), SettingType::String, 0, "界面语言"},
    {offsetof(GlobalPrefs, versionToSkip), SettingType::String, 0, nullptr},
    {offsetof(GlobalPrefs, windowState), SettingType::Int, 1, "窗口状态 1正常 2最大化 3全屏 4最小化"},
    {offsetof(GlobalPrefs, windowPos), SettingType::Compact, (intptr_t)&gRectInfo, "窗口位置与尺寸"},
    {offsetof(GlobalPrefs, searchUIWindowPos), SettingType::Compact, (intptr_t)&gRect_1_Info, "悬浮搜索窗位置"},
    {offsetof(GlobalPrefs, fileStates), SettingType::Array, (intptr_t)&gFileStateInfo, "各文档阅读状态"},
    {offsetof(GlobalPrefs, sessionData), SettingType::Array, (intptr_t)&gSessionDataInfo, "上次会话数据"},
    {offsetof(GlobalPrefs, reopenOnce), SettingType::StringArray, 0, nullptr},
    {offsetof(GlobalPrefs, timeOfLastUpdateCheck), SettingType::Compact, (intptr_t)&gFILETIMEInfo, "上次检测更新时间"},
    {offsetof(GlobalPrefs, timeOfUpdateCheckSnooze), SettingType::Compact, (intptr_t)&gFILETIME_1_Info,
     "更新提示推迟时间"},
    {offsetof(GlobalPrefs, openCountWeek), SettingType::Int, 0, "本周打开次数统计"},
    {offsetof(GlobalPrefs, propWinPos), SettingType::Compact, (intptr_t)&gPointInfo, nullptr},
    {(size_t)-1, SettingType::Comment, 0, nullptr},
    {(size_t)-1, SettingType::Comment, (intptr_t)"Settings below are not recognized by the current version",
     "Settings below are not recognized by the current version"},
};
static const StructInfo gGlobalPrefsInfo = {
    sizeof(GlobalPrefs), 139, gGlobalPrefsFields,
    "\0\0CheckForUpdates\0CustomScreenDPI\0DefaultDisplayMode\0DefaultZoom\0EnableTeXEnhancements\0EscToExit\0FullPathI"
    "nTitle\0InverseSearchCmdLine\0LazyLoading\0MainWindowBackground\0NoHomeTab\0HomePageSortByFrequentlyRead\0HomePage"
    "ViewMode\0HomePageThumbnailDx\0ReloadModifiedDocuments\0RememberOpenedFiles\0RememberStatePerDocument\0RestoreSess"
    "ion\0ReuseInstance\0ShowMenubar\0ShowMenubarWithTabs\0ShowTips\0CustomColors\0ShowToolbar\0ShowAnnotToolbarButtons"
    "\0SearchUIFloating\0OfflineDictionaryPath\0EnableDoubleClickWordLookup\0AutoOcrScanPages\0OcrAutoSave\0OcrDeskew\0"
    "OcrFullDocumentMode\0OcrCopyMerged\0ExtractPdfTocMode\0AiChatProvider\0AiTocApiBaseUrl\0AiTocApiKey\0AiTocApiModel"
    "\0AiTocApiProfiles\0AiTocApiConcurrency\0AiChatUseDeepSeekInsteadOfDoubao\0EnableAskAI\0EnableInlineTranslate\0Tra"
    "nslateVolcAccessKey\0TranslateVolcSecretKey\0TranslateTargetMode\0ShowFavorites\0ShowToc\0ShowLinks\0ShowStartPage"
    "\0SidebarDx\0Scrollbars\0ScrollbarInSinglePage\0SmoothScroll\0FastScrollOverScrollbar\0PreventSleepInFullscreen\0T"
    "abWidth\0TabFontSize\0TabBarHeight\0Theme\0LastDarkTheme\0LastLightTheme\0DocumentColorMode\0DocumentImageDarkStra"
    "tegy\0TocDy\0ToolbarSize\0TreeFontName\0TreeFontSize\0TreeWrapLabels\0UIFontSize\0DisableAntiAlias\0EngineeringDra"
    "wingEnhance\0UseSysColors\0UseTabs\0TabsMru\0ZoomLevels\0ZoomIncrement\0\0FixedPageUI\0\0EBookUI\0\0ComicBookUI\0"
    "\0ImageUI\0\0ChmUI\0\0Annotations\0\0ExternalViewers\0\0ForwardSearch\0\0PrinterDefaults\0\0Fullscreen\0\0Selectio"
    "nHandlers\0\0Shortcuts\0\0Themes\0\0TabGroups\0\0ReadAloudVoiceId\0ReadAloudSpeakingRate\0ReadAloudSpeakingRateZh"
    "\0ReadAloudSpeakingRateEn\0ReadAloudSmartVoiceZh\0ReadAloudSmartVoiceEn\0ReadAloudSmartOnlineVoiceZh\0ReadAloudSma"
    "rtOnlineVoiceEn\0ReadAloudMultilingualVoice\0ReadAloudHighlightColor\0ReadAloudAutoFollow\0NarrationUseBookAudio\0"
    "NarrationUseBookHighlightColor\0NarrationSpeed\0\0\0DefaultPasswords\0UiLanguage\0VersionToSkip\0WindowState\0Wind"
    "owPos\0SearchUIWindowPos\0FileStates\0SessionData\0ReopenOnce\0TimeOfLastUpdateCheck\0TimeOfUpdateCheckSnooze\0Ope"
    "nCountWeek\0PropWinPos\0\0"};
static const FieldInfo gTheme_1_Fields[] = {
    {offsetof(Theme, name), SettingType::String, (intptr_t)"", "主题名称"},
    {offsetof(Theme, textColor), SettingType::Color, (intptr_t)"", "文字颜色"},
    {offsetof(Theme, backgroundColor), SettingType::Color, (intptr_t)"", "背景颜色"},
    {offsetof(Theme, controlBackgroundColor), SettingType::Color, (intptr_t)"", "控件背景色"},
    {offsetof(Theme, linkColor), SettingType::Color, (intptr_t)"", "链接颜色"},
    {offsetof(Theme, colorizeControls), SettingType::Bool, false, "着色 Windows 控件"},
};
static const StructInfo gTheme_1_Info = {
    sizeof(Theme), 6, gTheme_1_Fields,
    "Name\0TextColor\0BackgroundColor\0ControlBackgroundColor\0LinkColor\0ColorizeControls"};

static const FieldInfo gThemesFields[] = {
    {offsetof(Themes, themes), SettingType::Array, (intptr_t)&gTheme_1_Info, "自定义主题"},
};
static const StructInfo gThemesInfo = {sizeof(Themes), 1, gThemesFields, "Themes"};

#endif
